// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function dropped(builder) {
  return (function (param, param$1) {
      builder.onDrop(param, param$1);
      return /* () */0;
    });
}

exports.dropped = dropped;
/* No side effect */
