// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function dropped(builder, string) {
  return (function (param, param$1) {
      builder.onDrop(string, param, param$1);
      return /* () */0;
    });
}

function removed(builder) {
  return (function (param) {
      builder.remove(param);
      return /* () */0;
    });
}

function bots(builder) {
  return builder.scene.bots;
}

function to_avatar(avatar_string) {
  if (avatar_string === "ninja") {
    return /* Some */[/* Ninja */0];
  } else {
    return /* None */0;
  }
}

exports.dropped   = dropped;
exports.removed   = removed;
exports.bots      = bots;
exports.to_avatar = to_avatar;
/* No side effect */
