// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Read$Slangwidge = require("slangwidge/src/read.bs.js");

function validate(script) {
  var program = Read$Slangwidge.read(script);
  if (program.tag) {
    return false;
  } else {
    return true;
  }
}

exports.validate = validate;
/* Read-Slangwidge Not a pure module */
