// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Read$Slangwidge = require("slangwidge/src/read.bs.js");

var script = "\n  walk right\n\n  on 'mock' do\n    shoot right\n  end\n";

Read$Slangwidge.read(script);

console.log("Hello, BuckleScript and Reason!");

exports.script = script;
/*  Not a pure module */
