// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry             = require("bs-platform/lib/js/curry.js");
var Pixi$Sweeneyville = require("./interop/pixi.bs.js");

function loader() {
  var loaded = [/* false */0];
  return (function (callback) {
      if (loaded[0]) {
        return Curry._1(callback, /* () */0);
      } else {
        var images = /* array */[
          "/images/tiles/tiles.jpeg",
          "/images/tiles/space.jpg",
          "/images/ninja_girl/Attack__000.png"
        ];
        return Pixi$Sweeneyville.App[/* load_textures */1](images, (function (_, _$1) {
                      Curry._1(callback, /* () */0);
                      loaded[0] = /* true */1;
                      return /* () */0;
                    }));
      }
    });
}

exports.loader = loader;
/* Pixi-Sweeneyville Not a pure module */
